package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class FoodRecipeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public FoodRecipeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFoodIdIsNull() {
			addCriterion("food_id is null");
			return (Criteria) this;
		}

		public Criteria andFoodIdIsNotNull() {
			addCriterion("food_id is not null");
			return (Criteria) this;
		}

		public Criteria andFoodIdEqualTo(Integer value) {
			addCriterion("food_id =", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdNotEqualTo(Integer value) {
			addCriterion("food_id <>", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdGreaterThan(Integer value) {
			addCriterion("food_id >", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("food_id >=", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdLessThan(Integer value) {
			addCriterion("food_id <", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdLessThanOrEqualTo(Integer value) {
			addCriterion("food_id <=", value, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdIn(List<Integer> values) {
			addCriterion("food_id in", values, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdNotIn(List<Integer> values) {
			addCriterion("food_id not in", values, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdBetween(Integer value1, Integer value2) {
			addCriterion("food_id between", value1, value2, "foodId");
			return (Criteria) this;
		}

		public Criteria andFoodIdNotBetween(Integer value1, Integer value2) {
			addCriterion("food_id not between", value1, value2, "foodId");
			return (Criteria) this;
		}

		public Criteria andRecipeDescIsNull() {
			addCriterion("recipe_desc is null");
			return (Criteria) this;
		}

		public Criteria andRecipeDescIsNotNull() {
			addCriterion("recipe_desc is not null");
			return (Criteria) this;
		}

		public Criteria andRecipeDescEqualTo(String value) {
			addCriterion("recipe_desc =", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescNotEqualTo(String value) {
			addCriterion("recipe_desc <>", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescGreaterThan(String value) {
			addCriterion("recipe_desc >", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescGreaterThanOrEqualTo(String value) {
			addCriterion("recipe_desc >=", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescLessThan(String value) {
			addCriterion("recipe_desc <", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescLessThanOrEqualTo(String value) {
			addCriterion("recipe_desc <=", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescLike(String value) {
			addCriterion("recipe_desc like", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescNotLike(String value) {
			addCriterion("recipe_desc not like", value, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescIn(List<String> values) {
			addCriterion("recipe_desc in", values, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescNotIn(List<String> values) {
			addCriterion("recipe_desc not in", values, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescBetween(String value1, String value2) {
			addCriterion("recipe_desc between", value1, value2, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andRecipeDescNotBetween(String value1, String value2) {
			addCriterion("recipe_desc not between", value1, value2, "recipeDesc");
			return (Criteria) this;
		}

		public Criteria andImageLocationIsNull() {
			addCriterion("image_location is null");
			return (Criteria) this;
		}

		public Criteria andImageLocationIsNotNull() {
			addCriterion("image_location is not null");
			return (Criteria) this;
		}

		public Criteria andImageLocationEqualTo(String value) {
			addCriterion("image_location =", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationNotEqualTo(String value) {
			addCriterion("image_location <>", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationGreaterThan(String value) {
			addCriterion("image_location >", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationGreaterThanOrEqualTo(String value) {
			addCriterion("image_location >=", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationLessThan(String value) {
			addCriterion("image_location <", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationLessThanOrEqualTo(String value) {
			addCriterion("image_location <=", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationLike(String value) {
			addCriterion("image_location like", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationNotLike(String value) {
			addCriterion("image_location not like", value, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationIn(List<String> values) {
			addCriterion("image_location in", values, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationNotIn(List<String> values) {
			addCriterion("image_location not in", values, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationBetween(String value1, String value2) {
			addCriterion("image_location between", value1, value2, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andImageLocationNotBetween(String value1, String value2) {
			addCriterion("image_location not between", value1, value2, "imageLocation");
			return (Criteria) this;
		}

		public Criteria andOrdIsNull() {
			addCriterion("ord is null");
			return (Criteria) this;
		}

		public Criteria andOrdIsNotNull() {
			addCriterion("ord is not null");
			return (Criteria) this;
		}

		public Criteria andOrdEqualTo(Integer value) {
			addCriterion("ord =", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotEqualTo(Integer value) {
			addCriterion("ord <>", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThan(Integer value) {
			addCriterion("ord >", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ord >=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThan(Integer value) {
			addCriterion("ord <", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdLessThanOrEqualTo(Integer value) {
			addCriterion("ord <=", value, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdIn(List<Integer> values) {
			addCriterion("ord in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotIn(List<Integer> values) {
			addCriterion("ord not in", values, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdBetween(Integer value1, Integer value2) {
			addCriterion("ord between", value1, value2, "ord");
			return (Criteria) this;
		}

		public Criteria andOrdNotBetween(Integer value1, Integer value2) {
			addCriterion("ord not between", value1, value2, "ord");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table food_recipe
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 26 10:17:21 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}