package com.example.demo.model;

public class FoodIngredients {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food_ingredients.food_id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	private Integer foodId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food_ingredients.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food_ingredients.food_id
	 * @return  the value of food_ingredients.food_id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public Integer getFoodId() {
		return foodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food_ingredients.food_id
	 * @param foodId  the value for food_ingredients.food_id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food_ingredients.name
	 * @return  the value of food_ingredients.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food_ingredients.name
	 * @param name  the value for food_ingredients.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}