package com.example.demo.model;

public class FoodType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food_type.id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food_type.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food_type.id
	 * @return  the value of food_type.id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food_type.id
	 * @param id  the value for food_type.id
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food_type.name
	 * @return  the value of food_type.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food_type.name
	 * @param name  the value for food_type.name
	 * @mbg.generated  Tue Nov 20 10:41:51 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}