package app.siba.mapper;

import app.siba.model.IngredientSubCategory;
import app.siba.model.IngredientSubCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IngredientSubCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	long countByExample(IngredientSubCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int deleteByExample(IngredientSubCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insert(IngredientSubCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insertSelective(IngredientSubCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	List<IngredientSubCategory> selectByExample(IngredientSubCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	IngredientSubCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExampleSelective(@Param("record") IngredientSubCategory record,
			@Param("example") IngredientSubCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExample(@Param("record") IngredientSubCategory record,
			@Param("example") IngredientSubCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByPrimaryKeySelective(IngredientSubCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_sub_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByPrimaryKey(IngredientSubCategory record);
}