package app.siba.mapper;

import app.siba.model.IngredientList;
import app.siba.model.IngredientListExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IngredientListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	long countByExample(IngredientListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int deleteByExample(IngredientListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insert(IngredientList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insertSelective(IngredientList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	List<IngredientList> selectByExample(IngredientListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExampleSelective(@Param("record") IngredientList record,
			@Param("example") IngredientListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_list
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExample(@Param("record") IngredientList record, @Param("example") IngredientListExample example);
}