package app.siba.mapper;

import app.siba.model.IngredientCategory;
import app.siba.model.IngredientCategoryExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IngredientCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	long countByExample(IngredientCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int deleteByExample(IngredientCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insert(IngredientCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int insertSelective(IngredientCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	List<IngredientCategory> selectByExample(IngredientCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	IngredientCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExampleSelective(@Param("record") IngredientCategory record,
			@Param("example") IngredientCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByExample(@Param("record") IngredientCategory record,
			@Param("example") IngredientCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByPrimaryKeySelective(IngredientCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ingredient_category
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	int updateByPrimaryKey(IngredientCategory record);
}