package com.example.demo.mapper;

import com.example.demo.model.FoodRecipe;
import com.example.demo.model.FoodRecipeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FoodRecipeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	long countByExample(FoodRecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	int deleteByExample(FoodRecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	int insert(FoodRecipe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	int insertSelective(FoodRecipe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	List<FoodRecipe> selectByExample(FoodRecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	int updateByExampleSelective(@Param("record") FoodRecipe record, @Param("example") FoodRecipeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table food_recipe
	 * @mbg.generated  Mon Nov 26 10:30:33 KST 2018
	 */
	int updateByExample(@Param("record") FoodRecipe record, @Param("example") FoodRecipeExample example);
}