package app.siba.model;

public class Food {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.food_type_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Integer foodTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.calorie
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Float calorie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.carbohydrate
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Float carbohydrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.protein
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Float protein;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.fat
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Float fat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.natrium
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Float natrium;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.small_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String smallImageLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.big_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String bigImageLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column food.ingredients
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String ingredients;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.id
	 * @return  the value of food.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.id
	 * @param id  the value for food.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.name
	 * @return  the value of food.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.name
	 * @param name  the value for food.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.food_type_id
	 * @return  the value of food.food_type_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Integer getFoodTypeId() {
		return foodTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.food_type_id
	 * @param foodTypeId  the value for food.food_type_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setFoodTypeId(Integer foodTypeId) {
		this.foodTypeId = foodTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.calorie
	 * @return  the value of food.calorie
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Float getCalorie() {
		return calorie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.calorie
	 * @param calorie  the value for food.calorie
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setCalorie(Float calorie) {
		this.calorie = calorie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.carbohydrate
	 * @return  the value of food.carbohydrate
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Float getCarbohydrate() {
		return carbohydrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.carbohydrate
	 * @param carbohydrate  the value for food.carbohydrate
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setCarbohydrate(Float carbohydrate) {
		this.carbohydrate = carbohydrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.protein
	 * @return  the value of food.protein
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Float getProtein() {
		return protein;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.protein
	 * @param protein  the value for food.protein
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setProtein(Float protein) {
		this.protein = protein;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.fat
	 * @return  the value of food.fat
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Float getFat() {
		return fat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.fat
	 * @param fat  the value for food.fat
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setFat(Float fat) {
		this.fat = fat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.natrium
	 * @return  the value of food.natrium
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Float getNatrium() {
		return natrium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.natrium
	 * @param natrium  the value for food.natrium
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setNatrium(Float natrium) {
		this.natrium = natrium;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.small_image_location
	 * @return  the value of food.small_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getSmallImageLocation() {
		return smallImageLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.small_image_location
	 * @param smallImageLocation  the value for food.small_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setSmallImageLocation(String smallImageLocation) {
		this.smallImageLocation = smallImageLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.big_image_location
	 * @return  the value of food.big_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getBigImageLocation() {
		return bigImageLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.big_image_location
	 * @param bigImageLocation  the value for food.big_image_location
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setBigImageLocation(String bigImageLocation) {
		this.bigImageLocation = bigImageLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column food.ingredients
	 * @return  the value of food.ingredients
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getIngredients() {
		return ingredients;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column food.ingredients
	 * @param ingredients  the value for food.ingredients
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setIngredients(String ingredients) {
		this.ingredients = ingredients;
	}
}