package app.siba.model;

public class IngredientCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_category.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_category.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_category.id
	 * @return  the value of ingredient_category.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_category.id
	 * @param id  the value for ingredient_category.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_category.name
	 * @return  the value of ingredient_category.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_category.name
	 * @param name  the value for ingredient_category.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}
}