package app.siba.model;

public class IngredientList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_list.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_list.ingredient_sub_category_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private Integer ingredientSubCategoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_list.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ingredient_list.file_name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	private String fileName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_list.id
	 * @return  the value of ingredient_list.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_list.id
	 * @param id  the value for ingredient_list.id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_list.ingredient_sub_category_id
	 * @return  the value of ingredient_list.ingredient_sub_category_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public Integer getIngredientSubCategoryId() {
		return ingredientSubCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_list.ingredient_sub_category_id
	 * @param ingredientSubCategoryId  the value for ingredient_list.ingredient_sub_category_id
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setIngredientSubCategoryId(Integer ingredientSubCategoryId) {
		this.ingredientSubCategoryId = ingredientSubCategoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_list.name
	 * @return  the value of ingredient_list.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_list.name
	 * @param name  the value for ingredient_list.name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ingredient_list.file_name
	 * @return  the value of ingredient_list.file_name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ingredient_list.file_name
	 * @param fileName  the value for ingredient_list.file_name
	 * @mbg.generated  Fri Nov 23 12:12:08 KST 2018
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
}